const palindromes = function(word) {
    //regex to test for special characters
    const format = /[` !@#$%^&*()_+\-=\[\]{};':"\\|,.<>\/?~]/;

    let testedWord = '';
    let newArr = '';

    //split string to an array, reverse array, join array, replace commas generated by being an array and change to lowercase
    let wordJoin = word.split("").reverse().join().replaceAll(",", "").toLowerCase();

    for (i = 0; i < wordJoin.length; i++) {
        if (format.test(wordJoin[i]) === false) {
            newArr += wordJoin[i];
        }
    }
    //iterate over the original word, change to lowercase - regex check for spec characters
    for (j = 0; j < word.length; j++) {
        if (format.test(word[j]) === false) {
            testedWord += word[j].toLowerCase();
            } 
    }

    //newWord = newArr.toLowerCase();
    console.log(`new string is ${newArr} and original string was ${testedWord}`)
    
    if (newArr == testedWord) {
        return true;
    } else {
        return false;
    }
}

module.exports = palindromes
